name: Maven CI

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - run: mkdir -p target

    - uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: target/cookiebot-*.jar

  docker:
   runs-on: ubuntu-latest
   needs: build
   permissions:
     contents: read
     packages: write

   steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Setup Docker buildx
       uses: docker/setup-buildx-action@v2.10.0

     - name: Log into registry ${{ env.REGISTRY }}
       uses: docker/login-action@v2
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Extract Docker metadata
       id: meta
       uses: docker/metadata-action@v4.6.0
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

     - name: Download build artifact
       uses: actions/download-artifact@v3
       with:
         name: build-artifact
         path: target/

     - name: Build and push Docker image
       id: build-and-push
       uses: docker/build-push-action@v4.1.1
       with:
         context: .
         platforms: linux/amd64
         file: Dockerfile
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
         cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
         cache-to: type=inline