name: Maven CI

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - run: mkdir -p target

    - uses: actions/upload-artifact@master
      with:
        path: target/cookiebot*.jar
