name: Maven CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 13
      uses: actions/setup-java@v1.1.0
      if: github.ref == 'refs/heads/master'
      with:
        java-version: 13

    - name: Build with Maven
      if: github.ref == 'refs/heads/master'
      run: mvn -B package --file pom.xml

    - run: mkdir -p target

    - uses: actions/upload-artifact@master
      with:
        name: cookiebot
        path: target
